query($issueIds: [ID!]!, $numIssuesToGet: Int!, $after: String) {
    nodes(ids: $issueIds) {
        ... on Issue {
            trackedIssues(first: $numIssuesToGet, after: $after) {
                nodes {
                    id
                }
                pageInfo { endCursor hasNextPage }
            }
        }
    }
}