query ($project: String!, $projectNumber: Int!, $fieldName: String!) {
  organization(login: $project) {
    projectV2(number: $projectNumber) {
      id
      field(name: $fieldName) {
        ... on ProjectV2FieldCommon {
          id
        }
        ... on ProjectV2SingleSelectField {
          options {
            name
            id
          }
        }
      }
    }
  }
}
