query($after: String) {
    organization(login: "llvm") {
        projectV2(number: 4) {
            items(first: 2, after: $after) {
                nodes {
                    updatedAt id                    
                    fieldValueByName(name: "Category") { ... on ProjectV2ItemFieldSingleSelectValue { name } }
                    content { ... on Issue { id updatedAt } }
                }
                pageInfo { endCursor hasNextPage }
            }
        }
    }
}