baseURL = 'https://llvm.github.io/wg-hlsl'
languageCode = 'en-us'
title = 'wg-hlsl'
theme = 'hugo-theme-techdoc'

[params]
  menu_style = "slide-menu"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']
  

[module]
  [[module.mounts]]
    source = './content'
    target= 'content'

  [[module.mounts]]
    source = '../docs'
    target = 'content/docs'
    
  [[module.mounts]]
    source = '../meetings'
    target = 'content/meetings'
  
  # Mount top-level README so the home page layout can read it
  [[module.mounts]]
    source = '../README.md'
    target = 'assets/readme.md'
  
  # Mount proposals as assets so the content adapter can ingest them without
  # Hugo treating them as regular content files directly (avoids collisions
  # and lets us enrich metadata programmatically).
  [[module.mounts]]
    source = '../proposals'
    target = 'assets/proposals'
    

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
